### ISSUE TITLE
Missing file Encoder.fs

### ISSUE THREAD

**Issue by vschep** [whitetigle/ElPouch#2]
After adding the dependency of ElPouch to my Fable project I get this error:

```
ERROR in ./src/IccpdPlusModel.fsproj
Module build failed (from ./node_modules/fable-loader/index.js):
Error: File does not exist: 
<some path>/.fable/ElPouch.0.0.6/ElPouch/Encoder.fs
    at Loader.fableUtils.client.send.then.r (<some path>\node_modules\fable-loader\index.js:67:22)
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js @babel/polyfill ./src/IccpdPlusModel.fsproj app[3]
```

When I add the missing file manualy from the ElPouch repo the build succeeds.

**Comment by whitetigle** [comment]
Thanks for the feedback!
Just changed that in the new version (0.0.7, currently publishing)

**Comment by vschep** [comment]
I confirm that 0.0.7 obtainted from nuget contains the missing file. Compiling succeeds. Thanks!

**Comment by whitetigle** [comment]
Great! Thanks for your feedback 👍
